/**
 * The 114 surahs: names and counts for SurahIndex. Generated by scripts/generateQuran.mjs.
 */

import type { SurahMeta } from "@/types/surah";

export const SURAHS: SurahMeta[] = [
  {
    "number": 1,
    "name": "سُورَةُ ٱلْفَاتِحَةِ",
    "englishName": "Al-Faatiha",
    "meaning": "The Opening",
    "ayahs": 7,
    "revelation": "Meccan"
  },
  {
    "number": 2,
    "name": "سُورَةُ البَقَرَةِ",
    "englishName": "Al-Baqara",
    "meaning": "The Cow",
    "ayahs": 286,
    "revelation": "Medinan"
  },
  {
    "number": 3,
    "name": "سُورَةُ آلِ عِمۡرَانَ",
    "englishName": "Aal-i-Imraan",
    "meaning": "The Family of Imraan",
    "ayahs": 200,
    "revelation": "Medinan"
  },
  {
    "number": 4,
    "name": "سُورَةُ النِّسَاءِ",
    "englishName": "An-Nisaa",
    "meaning": "The Women",
    "ayahs": 176,
    "revelation": "Medinan"
  },
  {
    "number": 5,
    "name": "سُورَةُ المَائـِدَةِ",
    "englishName": "Al-Maaida",
    "meaning": "The Table",
    "ayahs": 120,
    "revelation": "Medinan"
  },
  {
    "number": 6,
    "name": "سُورَةُ الأَنۡعَامِ",
    "englishName": "Al-An'aam",
    "meaning": "The Cattle",
    "ayahs": 165,
    "revelation": "Meccan"
  },
  {
    "number": 7,
    "name": "سُورَةُ الأَعۡرَافِ",
    "englishName": "Al-A'raaf",
    "meaning": "The Heights",
    "ayahs": 206,
    "revelation": "Meccan"
  },
  {
    "number": 8,
    "name": "سُورَةُ الأَنفَالِ",
    "englishName": "Al-Anfaal",
    "meaning": "The Spoils of War",
    "ayahs": 75,
    "revelation": "Medinan"
  },
  {
    "number": 9,
    "name": "سُورَةُ التَّوۡبَةِ",
    "englishName": "At-Tawba",
    "meaning": "The Repentance",
    "ayahs": 129,
    "revelation": "Medinan"
  },
  {
    "number": 10,
    "name": "سُورَةُ يُونُسَ",
    "englishName": "Yunus",
    "meaning": "Jonas",
    "ayahs": 109,
    "revelation": "Meccan"
  },
  {
    "number": 11,
    "name": "سُورَةُ هُودٍ",
    "englishName": "Hud",
    "meaning": "Hud",
    "ayahs": 123,
    "revelation": "Meccan"
  },
  {
    "number": 12,
    "name": "سُورَةُ يُوسُفَ",
    "englishName": "Yusuf",
    "meaning": "Joseph",
    "ayahs": 111,
    "revelation": "Meccan"
  },
  {
    "number": 13,
    "name": "سُورَةُ الرَّعۡدِ",
    "englishName": "Ar-Ra'd",
    "meaning": "The Thunder",
    "ayahs": 43,
    "revelation": "Medinan"
  },
  {
    "number": 14,
    "name": "سُورَةُ إِبۡرَاهِيمَ",
    "englishName": "Ibrahim",
    "meaning": "Abraham",
    "ayahs": 52,
    "revelation": "Meccan"
  },
  {
    "number": 15,
    "name": "سُورَةُ الحِجۡرِ",
    "englishName": "Al-Hijr",
    "meaning": "The Rock",
    "ayahs": 99,
    "revelation": "Meccan"
  },
  {
    "number": 16,
    "name": "سُورَةُ النَّحۡلِ",
    "englishName": "An-Nahl",
    "meaning": "The Bee",
    "ayahs": 128,
    "revelation": "Meccan"
  },
  {
    "number": 17,
    "name": "سُورَةُ الإِسۡرَاءِ",
    "englishName": "Al-Israa",
    "meaning": "The Night Journey",
    "ayahs": 111,
    "revelation": "Meccan"
  },
  {
    "number": 18,
    "name": "سُورَةُ الكَهۡفِ",
    "englishName": "Al-Kahf",
    "meaning": "The Cave",
    "ayahs": 110,
    "revelation": "Meccan"
  },
  {
    "number": 19,
    "name": "سُورَةُ مَرۡيَمَ",
    "englishName": "Maryam",
    "meaning": "Mary",
    "ayahs": 98,
    "revelation": "Meccan"
  },
  {
    "number": 20,
    "name": "سُورَةُ طه",
    "englishName": "Taa-Haa",
    "meaning": "Taa-Haa",
    "ayahs": 135,
    "revelation": "Meccan"
  },
  {
    "number": 21,
    "name": "سُورَةُ الأَنبِيَاءِ",
    "englishName": "Al-Anbiyaa",
    "meaning": "The Prophets",
    "ayahs": 112,
    "revelation": "Meccan"
  },
  {
    "number": 22,
    "name": "سُورَةُ الحَجِّ",
    "englishName": "Al-Hajj",
    "meaning": "The Pilgrimage",
    "ayahs": 78,
    "revelation": "Medinan"
  },
  {
    "number": 23,
    "name": "سُورَةُ المُؤۡمِنُونَ",
    "englishName": "Al-Muminoon",
    "meaning": "The Believers",
    "ayahs": 118,
    "revelation": "Meccan"
  },
  {
    "number": 24,
    "name": "سُورَةُ النُّورِ",
    "englishName": "An-Noor",
    "meaning": "The Light",
    "ayahs": 64,
    "revelation": "Medinan"
  },
  {
    "number": 25,
    "name": "سُورَةُ الفُرۡقَانِ",
    "englishName": "Al-Furqaan",
    "meaning": "The Criterion",
    "ayahs": 77,
    "revelation": "Meccan"
  },
  {
    "number": 26,
    "name": "سُورَةُ الشُّعَرَاءِ",
    "englishName": "Ash-Shu'araa",
    "meaning": "The Poets",
    "ayahs": 227,
    "revelation": "Meccan"
  },
  {
    "number": 27,
    "name": "سُورَةُ النَّمۡلِ",
    "englishName": "An-Naml",
    "meaning": "The Ant",
    "ayahs": 93,
    "revelation": "Meccan"
  },
  {
    "number": 28,
    "name": "سُورَةُ القَصَصِ",
    "englishName": "Al-Qasas",
    "meaning": "The Stories",
    "ayahs": 88,
    "revelation": "Meccan"
  },
  {
    "number": 29,
    "name": "سُورَةُ العَنكَبُوتِ",
    "englishName": "Al-Ankaboot",
    "meaning": "The Spider",
    "ayahs": 69,
    "revelation": "Meccan"
  },
  {
    "number": 30,
    "name": "سُورَةُ الرُّومِ",
    "englishName": "Ar-Room",
    "meaning": "The Romans",
    "ayahs": 60,
    "revelation": "Meccan"
  },
  {
    "number": 31,
    "name": "سُورَةُ لُقۡمَانَ",
    "englishName": "Luqman",
    "meaning": "Luqman",
    "ayahs": 34,
    "revelation": "Meccan"
  },
  {
    "number": 32,
    "name": "سُورَةُ السَّجۡدَةِ",
    "englishName": "As-Sajda",
    "meaning": "The Prostration",
    "ayahs": 30,
    "revelation": "Meccan"
  },
  {
    "number": 33,
    "name": "سُورَةُ الأَحۡزَابِ",
    "englishName": "Al-Ahzaab",
    "meaning": "The Clans",
    "ayahs": 73,
    "revelation": "Medinan"
  },
  {
    "number": 34,
    "name": "سُورَةُ سَبَإٍ",
    "englishName": "Saba",
    "meaning": "Sheba",
    "ayahs": 54,
    "revelation": "Meccan"
  },
  {
    "number": 35,
    "name": "سُورَةُ فَاطِرٍ",
    "englishName": "Faatir",
    "meaning": "The Originator",
    "ayahs": 45,
    "revelation": "Meccan"
  },
  {
    "number": 36,
    "name": "سُورَةُ يسٓ",
    "englishName": "Yaseen",
    "meaning": "Yaseen",
    "ayahs": 83,
    "revelation": "Meccan"
  },
  {
    "number": 37,
    "name": "سُورَةُ الصَّافَّاتِ",
    "englishName": "As-Saaffaat",
    "meaning": "Those drawn up in Ranks",
    "ayahs": 182,
    "revelation": "Meccan"
  },
  {
    "number": 38,
    "name": "سُورَةُ صٓ",
    "englishName": "Saad",
    "meaning": "The letter Saad",
    "ayahs": 88,
    "revelation": "Meccan"
  },
  {
    "number": 39,
    "name": "سُورَةُ الزُّمَرِ",
    "englishName": "Az-Zumar",
    "meaning": "The Groups",
    "ayahs": 75,
    "revelation": "Meccan"
  },
  {
    "number": 40,
    "name": "سُورَةُ غَافِرٍ",
    "englishName": "Ghafir",
    "meaning": "The Forgiver",
    "ayahs": 85,
    "revelation": "Meccan"
  },
  {
    "number": 41,
    "name": "سُورَةُ فُصِّلَتۡ",
    "englishName": "Fussilat",
    "meaning": "Explained in detail",
    "ayahs": 54,
    "revelation": "Meccan"
  },
  {
    "number": 42,
    "name": "سُورَةُ الشُّورَىٰ",
    "englishName": "Ash-Shura",
    "meaning": "Consultation",
    "ayahs": 53,
    "revelation": "Meccan"
  },
  {
    "number": 43,
    "name": "سُورَةُ الزُّخۡرُفِ",
    "englishName": "Az-Zukhruf",
    "meaning": "Ornaments of gold",
    "ayahs": 89,
    "revelation": "Meccan"
  },
  {
    "number": 44,
    "name": "سُورَةُ الدُّخَانِ",
    "englishName": "Ad-Dukhaan",
    "meaning": "The Smoke",
    "ayahs": 59,
    "revelation": "Meccan"
  },
  {
    "number": 45,
    "name": "سُورَةُ الجَاثِيَةِ",
    "englishName": "Al-Jaathiya",
    "meaning": "Crouching",
    "ayahs": 37,
    "revelation": "Meccan"
  },
  {
    "number": 46,
    "name": "سُورَةُ الأَحۡقَافِ",
    "englishName": "Al-Ahqaf",
    "meaning": "The Dunes",
    "ayahs": 35,
    "revelation": "Meccan"
  },
  {
    "number": 47,
    "name": "سُورَةُ مُحَمَّدٍ",
    "englishName": "Muhammad",
    "meaning": "Muhammad",
    "ayahs": 38,
    "revelation": "Medinan"
  },
  {
    "number": 48,
    "name": "سُورَةُ الفَتۡحِ",
    "englishName": "Al-Fath",
    "meaning": "The Victory",
    "ayahs": 29,
    "revelation": "Medinan"
  },
  {
    "number": 49,
    "name": "سُورَةُ الحُجُرَاتِ",
    "englishName": "Al-Hujuraat",
    "meaning": "The Inner Apartments",
    "ayahs": 18,
    "revelation": "Medinan"
  },
  {
    "number": 50,
    "name": "سُورَةُ قٓ",
    "englishName": "Qaaf",
    "meaning": "The letter Qaaf",
    "ayahs": 45,
    "revelation": "Meccan"
  },
  {
    "number": 51,
    "name": "سُورَةُ الذَّارِيَاتِ",
    "englishName": "Adh-Dhaariyat",
    "meaning": "The Winnowing Winds",
    "ayahs": 60,
    "revelation": "Meccan"
  },
  {
    "number": 52,
    "name": "سُورَةُ الطُّورِ",
    "englishName": "At-Tur",
    "meaning": "The Mount",
    "ayahs": 49,
    "revelation": "Meccan"
  },
  {
    "number": 53,
    "name": "سُورَةُ النَّجۡمِ",
    "englishName": "An-Najm",
    "meaning": "The Star",
    "ayahs": 62,
    "revelation": "Meccan"
  },
  {
    "number": 54,
    "name": "سُورَةُ القَمَرِ",
    "englishName": "Al-Qamar",
    "meaning": "The Moon",
    "ayahs": 55,
    "revelation": "Meccan"
  },
  {
    "number": 55,
    "name": "سُورَةُ الرَّحۡمَٰن",
    "englishName": "Ar-Rahmaan",
    "meaning": "The Beneficent",
    "ayahs": 78,
    "revelation": "Medinan"
  },
  {
    "number": 56,
    "name": "سُورَةُ الوَاقِعَةِ",
    "englishName": "Al-Waaqia",
    "meaning": "The Inevitable",
    "ayahs": 96,
    "revelation": "Meccan"
  },
  {
    "number": 57,
    "name": "سُورَةُ الحَدِيدِ",
    "englishName": "Al-Hadid",
    "meaning": "The Iron",
    "ayahs": 29,
    "revelation": "Medinan"
  },
  {
    "number": 58,
    "name": "سُورَةُ المُجَادلَةِ",
    "englishName": "Al-Mujaadila",
    "meaning": "The Pleading Woman",
    "ayahs": 22,
    "revelation": "Medinan"
  },
  {
    "number": 59,
    "name": "سُورَةُ الحَشۡرِ",
    "englishName": "Al-Hashr",
    "meaning": "The Exile",
    "ayahs": 24,
    "revelation": "Medinan"
  },
  {
    "number": 60,
    "name": "سُورَةُ المُمۡتَحنَةِ",
    "englishName": "Al-Mumtahana",
    "meaning": "She that is to be examined",
    "ayahs": 13,
    "revelation": "Medinan"
  },
  {
    "number": 61,
    "name": "سُورَةُ الصَّفِّ",
    "englishName": "As-Saff",
    "meaning": "The Ranks",
    "ayahs": 14,
    "revelation": "Medinan"
  },
  {
    "number": 62,
    "name": "سُورَةُ الجُمُعَةِ",
    "englishName": "Al-Jumu'a",
    "meaning": "Friday",
    "ayahs": 11,
    "revelation": "Medinan"
  },
  {
    "number": 63,
    "name": "سُورَةُ المُنَافِقُونَ",
    "englishName": "Al-Munaafiqoon",
    "meaning": "The Hypocrites",
    "ayahs": 11,
    "revelation": "Medinan"
  },
  {
    "number": 64,
    "name": "سُورَةُ التَّغَابُنِ",
    "englishName": "At-Taghaabun",
    "meaning": "Mutual Disillusion",
    "ayahs": 18,
    "revelation": "Medinan"
  },
  {
    "number": 65,
    "name": "سُورَةُ الطَّلَاقِ",
    "englishName": "At-Talaaq",
    "meaning": "Divorce",
    "ayahs": 12,
    "revelation": "Medinan"
  },
  {
    "number": 66,
    "name": "سُورَةُ التَّحۡرِيمِ",
    "englishName": "At-Tahrim",
    "meaning": "The Prohibition",
    "ayahs": 12,
    "revelation": "Medinan"
  },
  {
    "number": 67,
    "name": "سُورَةُ المُلۡكِ",
    "englishName": "Al-Mulk",
    "meaning": "The Sovereignty",
    "ayahs": 30,
    "revelation": "Meccan"
  },
  {
    "number": 68,
    "name": "سُورَةُ القَلَمِ",
    "englishName": "Al-Qalam",
    "meaning": "The Pen",
    "ayahs": 52,
    "revelation": "Meccan"
  },
  {
    "number": 69,
    "name": "سُورَةُ الحَاقَّةِ",
    "englishName": "Al-Haaqqa",
    "meaning": "The Reality",
    "ayahs": 52,
    "revelation": "Meccan"
  },
  {
    "number": 70,
    "name": "سُورَةُ المَعَارِجِ",
    "englishName": "Al-Ma'aarij",
    "meaning": "The Ascending Stairways",
    "ayahs": 44,
    "revelation": "Meccan"
  },
  {
    "number": 71,
    "name": "سُورَةُ نُوحٍ",
    "englishName": "Nooh",
    "meaning": "Noah",
    "ayahs": 28,
    "revelation": "Meccan"
  },
  {
    "number": 72,
    "name": "سُورَةُ الجِنِّ",
    "englishName": "Al-Jinn",
    "meaning": "The Jinn",
    "ayahs": 28,
    "revelation": "Meccan"
  },
  {
    "number": 73,
    "name": "سُورَةُ المُزَّمِّلِ",
    "englishName": "Al-Muzzammil",
    "meaning": "The Enshrouded One",
    "ayahs": 20,
    "revelation": "Meccan"
  },
  {
    "number": 74,
    "name": "سُورَةُ المُدَّثِّرِ",
    "englishName": "Al-Muddaththir",
    "meaning": "The Cloaked One",
    "ayahs": 56,
    "revelation": "Meccan"
  },
  {
    "number": 75,
    "name": "سُورَةُ القِيَامَةِ",
    "englishName": "Al-Qiyaama",
    "meaning": "The Resurrection",
    "ayahs": 40,
    "revelation": "Meccan"
  },
  {
    "number": 76,
    "name": "سُورَةُ الإِنسَانِ",
    "englishName": "Al-Insaan",
    "meaning": "Man",
    "ayahs": 31,
    "revelation": "Medinan"
  },
  {
    "number": 77,
    "name": "سُورَةُ المُرۡسَلَاتِ",
    "englishName": "Al-Mursalaat",
    "meaning": "The Emissaries",
    "ayahs": 50,
    "revelation": "Meccan"
  },
  {
    "number": 78,
    "name": "سُورَةُ النَّبَإِ",
    "englishName": "An-Naba",
    "meaning": "The Announcement",
    "ayahs": 40,
    "revelation": "Meccan"
  },
  {
    "number": 79,
    "name": "سُورَةُ النَّازِعَاتِ",
    "englishName": "An-Naazi'aat",
    "meaning": "Those who drag forth",
    "ayahs": 46,
    "revelation": "Meccan"
  },
  {
    "number": 80,
    "name": "سُورَةُ عَبَسَ",
    "englishName": "Abasa",
    "meaning": "He frowned",
    "ayahs": 42,
    "revelation": "Meccan"
  },
  {
    "number": 81,
    "name": "سُورَةُ التَّكۡوِيرِ",
    "englishName": "At-Takwir",
    "meaning": "The Overthrowing",
    "ayahs": 29,
    "revelation": "Meccan"
  },
  {
    "number": 82,
    "name": "سُورَةُ الانفِطَارِ",
    "englishName": "Al-Infitaar",
    "meaning": "The Cleaving",
    "ayahs": 19,
    "revelation": "Meccan"
  },
  {
    "number": 83,
    "name": "سُورَةُ المُطَفِّفِينَ",
    "englishName": "Al-Mutaffifin",
    "meaning": "Defrauding",
    "ayahs": 36,
    "revelation": "Meccan"
  },
  {
    "number": 84,
    "name": "سُورَةُ الانشِقَاقِ",
    "englishName": "Al-Inshiqaaq",
    "meaning": "The Splitting Open",
    "ayahs": 25,
    "revelation": "Meccan"
  },
  {
    "number": 85,
    "name": "سُورَةُ البُرُوجِ",
    "englishName": "Al-Burooj",
    "meaning": "The Constellations",
    "ayahs": 22,
    "revelation": "Meccan"
  },
  {
    "number": 86,
    "name": "سُورَةُ الطَّارِقِ",
    "englishName": "At-Taariq",
    "meaning": "The Morning Star",
    "ayahs": 17,
    "revelation": "Meccan"
  },
  {
    "number": 87,
    "name": "سُورَةُ الأَعۡلَىٰ",
    "englishName": "Al-A'laa",
    "meaning": "The Most High",
    "ayahs": 19,
    "revelation": "Meccan"
  },
  {
    "number": 88,
    "name": "سُورَةُ الغَاشِيَةِ",
    "englishName": "Al-Ghaashiya",
    "meaning": "The Overwhelming",
    "ayahs": 26,
    "revelation": "Meccan"
  },
  {
    "number": 89,
    "name": "سُورَةُ الفَجۡرِ",
    "englishName": "Al-Fajr",
    "meaning": "The Dawn",
    "ayahs": 30,
    "revelation": "Meccan"
  },
  {
    "number": 90,
    "name": "سُورَةُ البَلَدِ",
    "englishName": "Al-Balad",
    "meaning": "The City",
    "ayahs": 20,
    "revelation": "Meccan"
  },
  {
    "number": 91,
    "name": "سُورَةُ الشَّمۡسِ",
    "englishName": "Ash-Shams",
    "meaning": "The Sun",
    "ayahs": 15,
    "revelation": "Meccan"
  },
  {
    "number": 92,
    "name": "سُورَةُ اللَّيۡلِ",
    "englishName": "Al-Lail",
    "meaning": "The Night",
    "ayahs": 21,
    "revelation": "Meccan"
  },
  {
    "number": 93,
    "name": "سُورَةُ الضُّحَىٰ",
    "englishName": "Ad-Dhuhaa",
    "meaning": "The Morning Hours",
    "ayahs": 11,
    "revelation": "Meccan"
  },
  {
    "number": 94,
    "name": "سُورَةُ الشَّرۡحِ",
    "englishName": "Ash-Sharh",
    "meaning": "The Consolation",
    "ayahs": 8,
    "revelation": "Meccan"
  },
  {
    "number": 95,
    "name": "سُورَةُ التِّينِ",
    "englishName": "At-Tin",
    "meaning": "The Fig",
    "ayahs": 8,
    "revelation": "Meccan"
  },
  {
    "number": 96,
    "name": "سُورَةُ العَلَقِ",
    "englishName": "Al-Alaq",
    "meaning": "The Clot",
    "ayahs": 19,
    "revelation": "Meccan"
  },
  {
    "number": 97,
    "name": "سُورَةُ القَدۡرِ",
    "englishName": "Al-Qadr",
    "meaning": "The Power, Fate",
    "ayahs": 5,
    "revelation": "Meccan"
  },
  {
    "number": 98,
    "name": "سُورَةُ البَيِّنَةِ",
    "englishName": "Al-Bayyina",
    "meaning": "The Evidence",
    "ayahs": 8,
    "revelation": "Medinan"
  },
  {
    "number": 99,
    "name": "سُورَةُ الزَّلۡزَلَةِ",
    "englishName": "Az-Zalzala",
    "meaning": "The Earthquake",
    "ayahs": 8,
    "revelation": "Medinan"
  },
  {
    "number": 100,
    "name": "سُورَةُ العَادِيَاتِ",
    "englishName": "Al-Aadiyaat",
    "meaning": "The Chargers",
    "ayahs": 11,
    "revelation": "Meccan"
  },
  {
    "number": 101,
    "name": "سُورَةُ القَارِعَةِ",
    "englishName": "Al-Qaari'a",
    "meaning": "The Calamity",
    "ayahs": 11,
    "revelation": "Meccan"
  },
  {
    "number": 102,
    "name": "سُورَةُ التَّكَاثُرِ",
    "englishName": "At-Takaathur",
    "meaning": "Competition",
    "ayahs": 8,
    "revelation": "Meccan"
  },
  {
    "number": 103,
    "name": "سُورَةُ العَصۡرِ",
    "englishName": "Al-Asr",
    "meaning": "The Declining Day, Epoch",
    "ayahs": 3,
    "revelation": "Meccan"
  },
  {
    "number": 104,
    "name": "سُورَةُ الهُمَزَةِ",
    "englishName": "Al-Humaza",
    "meaning": "The Traducer",
    "ayahs": 9,
    "revelation": "Meccan"
  },
  {
    "number": 105,
    "name": "سُورَةُ الفِيلِ",
    "englishName": "Al-Fil",
    "meaning": "The Elephant",
    "ayahs": 5,
    "revelation": "Meccan"
  },
  {
    "number": 106,
    "name": "سُورَةُ قُرَيۡشٍ",
    "englishName": "Quraish",
    "meaning": "Quraysh",
    "ayahs": 4,
    "revelation": "Meccan"
  },
  {
    "number": 107,
    "name": "سُورَةُ المَاعُونِ",
    "englishName": "Al-Maa'un",
    "meaning": "Almsgiving",
    "ayahs": 7,
    "revelation": "Meccan"
  },
  {
    "number": 108,
    "name": "سُورَةُ الكَوۡثَرِ",
    "englishName": "Al-Kawthar",
    "meaning": "Abundance",
    "ayahs": 3,
    "revelation": "Meccan"
  },
  {
    "number": 109,
    "name": "سُورَةُ الكَافِرُونَ",
    "englishName": "Al-Kaafiroon",
    "meaning": "The Disbelievers",
    "ayahs": 6,
    "revelation": "Meccan"
  },
  {
    "number": 110,
    "name": "سُورَةُ النَّصۡرِ",
    "englishName": "An-Nasr",
    "meaning": "Divine Support",
    "ayahs": 3,
    "revelation": "Medinan"
  },
  {
    "number": 111,
    "name": "سُورَةُ المَسَدِ",
    "englishName": "Al-Masad",
    "meaning": "The Palm Fibre",
    "ayahs": 5,
    "revelation": "Meccan"
  },
  {
    "number": 112,
    "name": "سُورَةُ الإِخۡلَاصِ",
    "englishName": "Al-Ikhlaas",
    "meaning": "Sincerity",
    "ayahs": 4,
    "revelation": "Meccan"
  },
  {
    "number": 113,
    "name": "سُورَةُ الفَلَقِ",
    "englishName": "Al-Falaq",
    "meaning": "The Dawn",
    "ayahs": 5,
    "revelation": "Meccan"
  },
  {
    "number": 114,
    "name": "سُورَةُ النَّاسِ",
    "englishName": "An-Naas",
    "meaning": "Mankind",
    "ayahs": 6,
    "revelation": "Meccan"
  }
];
