/**
 * Generates the bundled Qur'an dataset from Al Quran Cloud (Tanzil Uthmani + Saheeh
 * International). Run once with Node 20: `node scripts/generateQuran.mjs`. Writes the
 * surah index and per-surah verse files under src/data/curated/quran/.
 */

import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/data/curated/quran");
const VERSES = join(OUT, "verses");

const get = async (u) => (await fetch(u)).json();
const clean = (s) => s.replace(/^﻿/, "").trim();

async function main() {
  const [meta, uth, sah] = await Promise.all([
    get("https://api.alquran.cloud/v1/surah").then((j) => j.data),
    get("https://api.alquran.cloud/v1/quran/quran-uthmani").then((j) => j.data),
    get("https://api.alquran.cloud/v1/quran/en.sahih").then((j) => j.data),
  ]);

  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(VERSES, { recursive: true });

  // The source prepends the Bismillah to ayah 1 of every surah; we strip it so it can
  // render as a header (Al-Fatihah keeps it as its ayah 1, At-Tawbah has none — D5).
  // Derived from Al-Fatihah's own ayah 1 so the encoding matches the source exactly.
  const BISMILLAH = clean(uth.surahs[0].ayahs[0].text);

  const index = meta.map((s) => ({
    number: s.number,
    name: s.name,
    englishName: s.englishName,
    meaning: s.englishNameTranslation,
    ayahs: s.numberOfAyahs,
    revelation: s.revelationType,
  }));

  for (let i = 0; i < 114; i++) {
    const num = i + 1;
    const ar = uth.surahs[i].ayahs;
    const en = sah.surahs[i].ayahs;
    const verses = ar.map((a, j) => {
      let arabic = clean(a.text);
      if (j === 0 && num !== 1 && arabic.startsWith(BISMILLAH)) {
        arabic = arabic.slice(BISMILLAH.length).trim();
      }
      return { verse: a.numberInSurah, arabic, translation: clean(en[j].text) };
    });
    writeFileSync(join(VERSES, `${num}.json`), JSON.stringify(verses));
  }

  const indexTs = `/**
 * The 114 surahs: names and counts for SurahIndex. Generated by scripts/generateQuran.mjs.
 */

import type { SurahMeta } from "@/types/surah";

export const SURAHS: SurahMeta[] = ${JSON.stringify(index, null, 2)};
`;
  writeFileSync(join(OUT, "surahs.ts"), indexTs);

  const lines = Array.from(
    { length: 114 },
    (_, k) => `  ${k + 1}: () => require("./verses/${k + 1}.json") as unknown as AyahText[],`
  ).join("\n");
  const loaderTs = `/**
 * Lazy per-surah verse loader. A surah's JSON is parsed only when first opened, so the
 * whole mushaf never sits in memory at once. Generated by scripts/generateQuran.mjs.
 */

import type { AyahText } from "@/types/surah";

const LOADERS: Record<number, () => AyahText[]> = {
${lines}
};

export function loadSurah(n: number): AyahText[] {
  return LOADERS[n]?.() ?? [];
}
`;
  writeFileSync(join(OUT, "index.ts"), loaderTs);

  // sanity checks on the two Bismillah edge cases
  const fatiha = JSON.parse((await import("node:fs")).readFileSync(join(VERSES, "1.json")));
  const tawbah = JSON.parse((await import("node:fs")).readFileSync(join(VERSES, "9.json")));
  console.log("wrote", index.length, "surahs");
  console.log("Al-Fatihah ayah1:", fatiha[0].arabic);
  console.log("At-Tawbah ayah1:", tawbah[0].arabic.slice(0, 50));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
